-- Usar la base de datos "OutShoes"

USE `OutShoes`;

-- Insertar marcas en la tabla "marca"

INSERT INTO `marca` (nombre) VALUES ('Adidas');
INSERT INTO `marca` (nombre) VALUES ('Converse');
INSERT INTO `marca` (nombre) VALUES ('Disney');
INSERT INTO `marca` (nombre) VALUES ('Dockers');
INSERT INTO `marca` (nombre) VALUES ('Efe');
INSERT INTO `marca` (nombre) VALUES ('Gonsa');
INSERT INTO `marca` (nombre) VALUES ('Gosh');
INSERT INTO `marca` (nombre) VALUES ('Lenmarq');
INSERT INTO `marca` (nombre) VALUES ('Levis');
INSERT INTO `marca` (nombre) VALUES ('Nike');
INSERT INTO `marca` (nombre) VALUES ('Paulina');
INSERT INTO `marca` (nombre) VALUES ('Perez Lete');
INSERT INTO `marca` (nombre) VALUES ('Ruiditos');
INSERT INTO `marca` (nombre) VALUES ('Sesamo');
INSERT INTO `marca` (nombre) VALUES ('Tropicana');

-- Insertar categorías en la tabla "categoria"

INSERT INTO `categoria` (nombre) VALUES ('Hombre');
INSERT INTO `categoria` (nombre) VALUES ('Mujer');
INSERT INTO `categoria` (nombre) VALUES ('Niña');
INSERT INTO `categoria` (nombre) VALUES ('Niño');

-- Insertar tipos de usuario en la tabla "tipo"

INSERT INTO `tipo` (nombre) VALUES ("administrador");
INSERT INTO `tipo` (nombre) VALUES ("cliente");

-- Insertar las colecciones en la tabla "Coleccion"

INSERT INTO `coleccion` (nombre) VALUES ('Botas');
INSERT INTO `coleccion` (nombre) VALUES ('Pantuflas');
INSERT INTO `coleccion` (nombre) VALUES ('Sandalias');
INSERT INTO `coleccion` (nombre) VALUES ('Tenis');
INSERT INTO `coleccion` (nombre) VALUES ('Zapatillas');
INSERT INTO `coleccion` (nombre) VALUES ('Zapato');

-- Insertar los estados del pedido en la tabla "estadopedido"

INSERT INTO `estado` (nombre) VALUES ('Devuelto');
INSERT INTO `estado` (nombre) VALUES ('Empaquetado');
INSERT INTO `estado` (nombre) VALUES ('Enviado');
INSERT INTO `estado` (nombre) VALUES ('Pagado');
INSERT INTO `estado` (nombre) VALUES ('Pago en proceso');
INSERT INTO `estado` (nombre) VALUES ('Recibido');
INSERT INTO `estado` (nombre) VALUES ('Sin pagar');

-- Insertar las tallas 

INSERT INTO `talla` (numero) VALUES ('8');
INSERT INTO `talla` (numero) VALUES ('8.5');
INSERT INTO `talla` (numero) VALUES ('9');
INSERT INTO `talla` (numero) VALUES ('9.5');
INSERT INTO `talla` (numero) VALUES ('10');
INSERT INTO `talla` (numero) VALUES ('10.5');
INSERT INTO `talla` (numero) VALUES ('11');
INSERT INTO `talla` (numero) VALUES ('11.5');
INSERT INTO `talla` (numero) VALUES ('12');
INSERT INTO `talla` (numero) VALUES ('12.5');
INSERT INTO `talla` (numero) VALUES ('13');
INSERT INTO `talla` (numero) VALUES ('13.5');
INSERT INTO `talla` (numero) VALUES ('14');
INSERT INTO `talla` (numero) VALUES ('14.5');
INSERT INTO `talla` (numero) VALUES ('15');
INSERT INTO `talla` (numero) VALUES ('15.5');
INSERT INTO `talla` (numero) VALUES ('16');
INSERT INTO `talla` (numero) VALUES ('16.5');
INSERT INTO `talla` (numero) VALUES ('17');
INSERT INTO `talla` (numero) VALUES ('17.5');
INSERT INTO `talla` (numero) VALUES ('18');
INSERT INTO `talla` (numero) VALUES ('18.5');
INSERT INTO `talla` (numero) VALUES ('19');
INSERT INTO `talla` (numero) VALUES ('19.5');
INSERT INTO `talla` (numero) VALUES ('20');
INSERT INTO `talla` (numero) VALUES ('20.5');
INSERT INTO `talla` (numero) VALUES ('21');
INSERT INTO `talla` (numero) VALUES ('21.5');
INSERT INTO `talla` (numero) VALUES ('22');
INSERT INTO `talla` (numero) VALUES ('22.5');
INSERT INTO `talla` (numero) VALUES ('23');
INSERT INTO `talla` (numero) VALUES ('23.5');
INSERT INTO `talla` (numero) VALUES ('24');
INSERT INTO `talla` (numero) VALUES ('24.5');
INSERT INTO `talla` (numero) VALUES ('25');
INSERT INTO `talla` (numero) VALUES ('25.5');
INSERT INTO `talla` (numero) VALUES ('26');
INSERT INTO `talla` (numero) VALUES ('26.5');
INSERT INTO `talla` (numero) VALUES ('27');
INSERT INTO `talla` (numero) VALUES ('27.5');
INSERT INTO `talla` (numero) VALUES ('28');
INSERT INTO `talla` (numero) VALUES ('28.5');
INSERT INTO `talla` (numero) VALUES ('29');
INSERT INTO `talla` (numero) VALUES ('29.5');
INSERT INTO `talla` (numero) VALUES ('30');

-- Usuarios
INSERT INTO `usuario` (correo, contrasena, nombre, apellidop, apellidom, direccionuno, direcciondos, estado, ciudad, cp, Tipo_id) VALUES ("tyron@outshoes.com", "papitas123", "Tyron", "Vergara", "Guerra", "Enrique Segoviano, 8", "Departamento 8", "Ciudad de México", "Azcapotzalco", "02100", 1); 
INSERT INTO `usuario` (correo, contrasena, nombre, apellidop, apellidom, direccionuno, direcciondos, estado, ciudad, cp, Tipo_id) VALUES ("daniela@outshoes.com", "morado321", "Daniela", "Moreno", "Pérez", "Primera Avenida 12", "Edificio 2", "Tamaulipas", "Tampico", "89300", 1);
INSERT INTO `usuario` (correo, contrasena, nombre, apellidop, apellidom, direccionuno, direcciondos, estado, ciudad, cp, Tipo_id) VALUES ("hector@outshoes.com", "Pa$$w0rd987", "Héctor", "Zamora", "Bringas", "Donceles 815", "Planta baja", "Ciudad de México", "Cuauhtemoc", "06000", 1);
INSERT INTO `usuario` (correo, contrasena, nombre, apellidop, apellidom, direccionuno, direcciondos, estado, ciudad, cp, Tipo_id) VALUES ("gabo@outshoes.com", "paola08", "Gabriel", "Malacara", "Roman", "Condesa de Coslada 144", "La Condesa", "Guanajuato", "León", "37440", 1);
INSERT INTO `usuario` (correo, contrasena, nombre, apellidop, apellidom, direccionuno, direcciondos, estado, ciudad, cp, Tipo_id) VALUES ("antonio@outshoes.com", "amotecamac@", "Antonio", "Jorge", "Bonilla", "Aureliano Rivera 26", "Privada Girasoles", "Estado de México", "Tecamac", "01000", 1);


-- Productos

INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('ADD2007', 'Tenis Adidas para Hombre GZ5306 Blanco', 'TENIS ADVANTAGE LOS SIMPSONS TENIS CON UN CORTE MODERNO Y ESTILO VINTAGE. Inyéctale un poco de energía vintage a tu estilo moderno con estos tenis adidas. Inspirados en el calzado clásico de tenis, el exterior textil y la suela de caucho ofrecen comodidad con cada paso y un estilo retro único. Los estampados que rinden homenaje a la familia disfuncional favorita de la televisión, los Simpsons, les imprime un toque de modernidad.', './img/item/1.webp', '1599', 1, 4, 1);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('EFE1001', 'Zapatillas Efe para Mujer 228201 Plateado', 'Zapatilla con tiras delgadas con detalles de estoperoles a tono. Cuenta con tira en tobillo ajustable con hebilla.', './img/item/2.webp', '739', 2, 5, 5);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('LEV149', 'Bota Casual Levis para Hombre L211332 Cafe', 'Bota urbana con estilo atemporal fabricada en piel cuyo acabado rústico lo hace ideal para lograr un look casual, te recomendamos usarlos con tus Levi´s 511™', './img/item/3.webp', '1599', 1, 1, 9);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('LEM9', 'Pantuflas Lenmarq para Niña 3005 Beige', 'Hermosas Pantuflas Lenmarq para niña color maquillaje, tu pequeña será la envidia de todas con estas excelentes pantuflas.', './img/item/4.webp', '320', 3, 2, 8);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('NIK2349', 'Sandalias Nike para Niño 819352-001 Negro', 'La chancla Nike Kawa es son superfáciles de ponerse en cualquier momento. Con un diseño suave y flexible, estas sandalias ayudan a los pies en crecimiento a recuperarse después de la práctica, el juego o cualquier aventura (como un día en la playa).', './img/item/5.webp', '599', 4, 3, 10);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('CVR14', 'Tenis Converse para Hombre 7650 Blanco', 'Necesitas un estilo infalible. El Chuck Taylor All-Star es un elemento esencial: el perfil alto y el estilo oxford brindan una apariencia verdaderamente clásica, a la vez que los cordones blancos y el parche de estrella en el tobillo rinden homenaje al legado del Chuck. Este es el calzado que combina con todo que no te cansarás de usar.', './img/item/6.webp', '1299', 1, 4, 2);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('PLT227', 'Botín Perez lete para Mujer 33191 Negro ', 'Hermosa bota Perez Lete con Corte Sintetico en Charol Negro. Este calzado te hará ver de maravilla a donde quiera que vayas. ', './img/item/7.webp', '1299', 2, 1, 12);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('SES4', 'Pantuflas Sesamo para Niño 93200-1-C Azul ', 'Los pies siempre estarán calientitos con la nuevas pantuflas modelo Peluche de Sésamo. Están elaboradas en suave textil. Su suela es ligera y súper acojinada. Están personalizadas con el Come Galletas. ', './img/item/8.webp', '329', 4, 2, 14);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('TRO1201', 'Sandalias Tropicana para Niña 19036 Rosa ', 'Sandalias con adorable estampado de conejito, resorte ajustable a los piesitos de tu pequeña, suela ligera; antiderrapante, hecho de material de alta calidad. Que tu niña lleve la magia a todos lados. Fácil de combinar con diversos outfits para a si lucir linda y a la moda. Perfecta para el uso diario Cómoda para vivir una experiencia agradable, fácil de quitar y llevar a todos lados. ', './img/item/9.webp', '289', 3, 3, 15);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('DCK68', 'Zapato de Vestir Dockers para Hombre D219571 Negro', 'Luce pulcro y elegante con estos zapatos para caballero de Dockers, Un clásico en negro con agujetas ajustables para mayor seguridad. Ideal para combinarlos con estilos formales. Siéntete increíble y deslumbra en cualquier evento importante con tus Dockers. ', './img/item/10.webp', '1369', 1, 6, 4);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('ADD1802', 'Tenis Adidas para Hombre FX3593 Negr', 'TENIS CORERACER TENIS DE RUNNING LIVIANOS PARA UNA TOTAL COMODIDAD Los tenis adidas Coreracer ofrecen la combinación perfecta de sujeción para running y estilo urbano. Son livianos y transpirables para mantener tus pies cómodos en todo momento. Lucen un logo adidas Badge of Sport que le pone el toque final al look de alto rendimiento.', './img/item/11.webp', '1199', 1, 4, 1);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('DCK99', 'Bota Casual Dockers para Hombre D221624 Cafe ', 'Bota para caballero 100% original moderna y elegante, su estilo elegante y vanguardista la convierten en el calzado ideal para vestir a la moda con comodidad debido a su interior acojinado, suela antideslizante.', './img/item/12.webp', '1399', 1, 1, 4);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('NIK2466', 'Tenis Nike para Mujer CQ9545-014 Violeta oscuro ', 'El Nike Legend Essential 2 viene equipado con un talón plano y estable, flexibilidad debajo de la punta y soporte de lado a lado. Gracias a su gran agarre, puedes hacer levantamientos, entrenamientos de alta intensidad, conquistar una clase o fortalecerte en las máquinas.', './img/item/13.webp', '1349', 2, 4, 10);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('DNY29', 'Tenis Disney para Niña 73043 Blanco', 'Estos Hermosos Tenis son perfectos para tu pequeños con sus personajes favoritos de Minnie Mouse. Quedarán Asombrados.', './img/item/14.webp', '599', 3, 4, 3);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('RDI5', 'Bota Ruditos para Niño 2800 Cafe ', 'Para que tu pequeño luzca a la moda estos Zapatos Botín en color café son los indicados. Su diseño de ajuste de cintas y son la combinación perfecta para combinar con infinidad de atuendos a la moda y lucir super ligero y confiable a la hora de caminar.', './img/item/15.webp', '409', 4, 1, 13);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('GNS95', 'Zapatillas para Mujer 10562 Negro', 'Hermosa zapatilla con un diseño único que te hará lucir fabulosa en todo momento. Su diseño de abertura y elegante moño en la parte del empeine, le añaden un toque único y fashionista. La altura de su tacón es perfecto para hacerte lucir más estilizada. ', './img/item/16.webp', '499', 2, 5, 6);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('DCK89', 'Bota Casual para Hombre D211612', 'La tradición y herencia artesanal conjugadas en un look casual hecho zapato. ', './img/item/17.webp', '1699', 1, 1, 4);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('PAU806', 'Bota Paulina para Mujer 84218', 'Bota adecuadas para todas las mujeres de la casa. No pueden faltar en tu guardarropa de esta temporada. Bota de gamusin con suela antiderrapante ideales para verte bien esta temporada. ', './img/item/18.webp', '659', 2, 1, 11);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('TRO1036', 'Flats Tropicana para Niña 31761', 'Hermosa ballerina en color Rosa para tu pequeña, con adorable moño al frente que añade un toque divertido a su estilo.Hecha de material sintético en acabado mate, con tira elástica ajustable y fácil de quitar y llevar a todos lados, cuenta con suela ligera y antiderrapante. ', './img/item/19.webp', '259', 3, 6, 15);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('RDI7', 'Zapato Casual para Niño 2602', 'Para que tu pequeño luzca a la moda estos Zapatos en color café son los indicados. Su diseño de ajuste de cintas y son la combinación perfecta para combinar con infinidad de atuendos a la moda y lucir super ligero y confiable a la hora de caminar. ', './img/item/20.webp', '399', 4, 6, 13);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('ADD1965', 'Sandalias Adidas para Niña FY8072 Rosa', 'SANDALIAS ADILETTE AQUA SANDALIAS SUAVES PARA EL AGUA Destaca su amor por adidas con estas sandalias adidas. Su diseño con banda superior de una sola pieza moldeada y las 3 Franjas es perfecta para la ducha o antes y después de la alberca. La plantilla supersuave es de secado rápido para mantener sus pies cómodos en todo momento. ', './img/item/21.webp', '499', 3, 3, 1);
INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('GOS898', 'Bota Gosh para Niña 14353-01 Rosa ', 'Este hermoso botín color rosa hará lucir increíble a tu niña y harás notar su presencia en cualquier lugar. le darán esa comodidad que necesita al caminar, además que sus cintas son perfectas para ajustarse perfecto a tu pie. ', './img/item/22.webp', '429', 3, 1, 7);
-- INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('ADD2007', 'Tenis Adidas para Hombre GZ5306 Blanco ', 'TENIS ADVANTAGE LOS SIMPSONS TENIS CON UN CORTE MODERNO Y ESTILO VINTAGE. Inyéctale un poco de energía vintage a tu estilo moderno con estos tenis adidas. Inspirados en el calzado clásico de tenis, el exterior textil y la suela de caucho ofrecen comodidad con cada paso y un estilo retro único. Los estampados que rinden homenaje a la familia disfuncional favorita de la televisión, los Simpsons, les imprime un toque de modernidad. ', './img/item/23.webp', '1599', 1, 4, 1);
-- INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('CVR5', 'Tenis Converse para Mujer 9166 Negro ', 'Necesitas un estilo infalible. El Chuck Taylor All-Star es un elemento esencial: el perfil alto y el estilo oxford brindan una apariencia verdaderamente clásica, a la vez que los cordones blancos y el parche de estrella en el tobillo rinden homenaje al legado del Chuck. Este es el calzado que combina con todo que no te cansarás de usar. ', './img/item/24.webp', '1249', 2, 4, 2);
-- INSERT INTO `producto` (sku, nombre, descripcion, imagen, precio, Categoria_id, Coleccion_id, Marca_id) VALUES ('ADD2082', 'Tenis Adidas para Niña GY5438 Blanco ', 'El día de los niños está lleno de actividades, por lo que necesitan un calzado que pueda seguir su ritmo. Estos tenis adidas para niños están inspirados en el clásico estilo tenístico. Incorporan tres tiras ajustables de cierre por contacto sobre un exterior de piel sintética para una sensación de sujeción y máxima comodidad. Los estampados en el exterior le permiten llevar a sus personajes favoritos de la película Frozen de Disney adondequiera que vaya. ', './img/item/25.webp', '999', 3, 4, 1);

-- Insertar registros en "Inventario"

INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (1, 35);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (1, 36);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (1, 37);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (1, 38);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (1, 39);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (1, 40);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (1, 41);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (2, 29);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (2, 30);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (2, 31);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (2, 32);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (2, 33);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (2, 34);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (2, 35);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (3, 37);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (3, 38);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (3, 39);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (3, 40);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (3, 41);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (3, 42);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (3, 43);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (4, 21);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (4, 22);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (4, 23);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (4, 24);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (4, 25);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (4, 26);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (4, 27);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (5, 29);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (5, 30);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (5, 31);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (5, 32);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (5, 33);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (5, 34);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (5, 35);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (6, 31);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (6, 32);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (6, 33);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (6, 34);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (6, 35);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (6, 36);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (6, 37);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (7, 37);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (7, 38);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (7, 39);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (7, 40);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (7, 41);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (7, 42);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (7, 43);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (8, 19);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (8, 20);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (8, 21);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (8, 22);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (8, 23);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (8, 24);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (8, 25);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (9, 9);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (9, 10);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (9, 11);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (9, 12);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (9, 13);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (9, 14);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (9, 15);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (10, 39);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (10, 40);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (10, 41);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (10, 42);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (10, 43);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (10, 44);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (10, 45);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (11, 35);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (11, 36);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (11, 37);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (11, 38);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (11, 39);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (11, 40);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (11, 41);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (12, 37);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (12, 38);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (12, 39);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (12, 40);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (12, 41);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (12, 42);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (12, 43);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (13, 29);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (13, 30);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (13, 31);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (13, 32);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (13, 33);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (13, 34);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (13, 35);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (14, 19);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (14, 20);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (14, 21);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (14, 22);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (14, 23);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (14, 24);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (14, 25);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (15, 19);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (15, 20);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (15, 21);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (15, 22);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (15, 23);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (15, 24);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (15, 25);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (16, 31);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (16, 32);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (16, 33);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (16, 34);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (16, 35);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (16, 36);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (16, 37);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (17, 37);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (17, 38);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (17, 39);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (17, 40);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (17, 41);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (17, 42);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (17, 43);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (18, 31);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (18, 32);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (18, 33);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (18, 34);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (18, 35);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (18, 36);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (18, 37);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (19, 9);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (19, 10);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (19, 11);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (19, 12);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (19, 13);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (19, 14);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (19, 15);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (20, 21);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (20, 22);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (20, 23);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (20, 24);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (20, 25);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (20, 26);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (20, 27);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (21, 27);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (21, 28);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (21, 29);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (21, 30);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (21, 31);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (21, 32);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (21, 33);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (22, 21);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (22, 22);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (22, 23);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (22, 24);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (22, 25);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (22, 26);
INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (22, 27);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (23, 35);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (23, 36);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (23, 37);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (23, 38);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (23, 39);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (23, 40);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (23, 41);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (24, 31);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (24, 32);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (24, 33);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (24, 34);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (24, 35);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (24, 36);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (24, 37);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (25, 19);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (25, 20);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (25, 21);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (25, 22);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (25, 23);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (25, 24);
-- INSERT INTO `inventario`(Producto_id, Talla_id) VALUES (25, 25);

-- Insertar existencias por talla

INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (1, 3);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (1, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (1, 6);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (1, 0);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (1, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (1, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (1, 0);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (2, 3);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (2, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (2, 1);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (2, 8);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (2, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (2, 8);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (2, 8);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (3, 1);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (3, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (3, 5);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (3, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (3, 3);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (3, 2);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (3, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (4, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (4, 2);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (4, 1);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (4, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (4, 0);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (4, 6);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (4, 2);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (5, 1);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (5, 6);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (5, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (5, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (5, 0);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (5, 3);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (5, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (6, 0);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (6, 2);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (6, 6);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (6, 1);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (6, 5);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (6, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (6, 1);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (7, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (7, 8);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (7, 6);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (7, 0);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (7, 1);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (7, 8);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (7, 2);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (8, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (8, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (8, 6);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (8, 3);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (8, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (8, 1);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (8, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (9, 3);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (9, 5);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (9, 3);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (9, 0);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (9, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (9, 6);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (9, 5);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (10, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (10, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (10, 0);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (10, 6);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (10, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (10, 8);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (10, 1);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (11, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (11, 8);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (11, 8);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (11, 6);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (11, 8);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (11, 5);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (11, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (12, 1);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (12, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (12, 2);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (12, 3);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (12, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (12, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (12, 5);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (13, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (13, 8);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (13, 5);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (13, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (13, 3);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (13, 5);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (13, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (14, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (14, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (14, 1);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (14, 0);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (14, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (14, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (14, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (15, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (15, 2);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (15, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (15, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (15, 0);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (15, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (15, 8);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (16, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (16, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (16, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (16, 6);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (16, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (16, 1);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (16, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (17, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (17, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (17, 8);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (17, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (17, 8);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (17, 1);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (17, 0);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (18, 1);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (18, 8);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (18, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (18, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (18, 6);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (18, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (18, 1);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (19, 6);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (19, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (19, 6);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (19, 5);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (19, 7);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (19, 6);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (19, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (20, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (20, 3);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (20, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (20, 0);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (20, 3);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (20, 0);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (20, 6);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (21, 8);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (21, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (21, 8);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (21, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (21, 4);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (21, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (21, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (22, 0);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (22, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (22, 6);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (22, 9);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (22, 0);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (22, 3);
INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (22, 1);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (23, 5);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (23, 5);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (23, 7);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (23, 2);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (23, 1);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (23, 9);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (23, 4);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (24, 4);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (24, 0);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (24, 4);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (24, 5);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (24, 7);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (24, 5);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (24, 7);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (25, 7);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (25, 3);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (25, 9);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (25, 7);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (25, 6);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (25, 2);
-- INSERT INTO `existencia` (Inventario_id, cantidad) VALUES (25, 9);
